databases:
  - name: pledgecity-db
    plan: free
    databaseName: pledgecity
    user: pledgecity

services:
  - type: web
    name: pledgecity
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pledgecity-db
          property: connectionString
      - key: SEED_DEMO
        value: "false"
